source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FluidValidator_Tests' do
  pod 'FluidValidator', :path => '../'
end

target 'ExampleApp' do
    pod 'FluidValidator', :path => '../'
end
